project:
  type: website
  output-dir: docs

website:
  title: "Learning Azure Cloud Infrastructure - Themes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - azure-governance.qmd
      - azure-compute.qmd
      - azure-storage-non-relational.qmd
      - azure-storage-relational.qmd
      - azure-data-integration.qmd
      - azure-application-architecture.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
